name: llama3-8b-q6k
type: llama
quantization: q6k # or q4_0, depending on your hardware and model size
revision: main # or a specific commit hash if needed
temperature: 0.7
top_p: 0.95
max_new_tokens: 512
repetition_penalty: 1.2
seed: 42
