# Base configuration for the RAG Fusion Pipeline.
# Parameters marked as "???" have to be specified.
# All other parameters can be overridden by the command line or other configuration
# files.

# Note that whatever is in the main config file will override the defaults
# and not the other way around.

defaults: # these are the sub-config files for specific details, noee for the moment.
  - _self_ # this makes the top-level config take priority over sub-configs, see https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order/
  - model: model
  - llm_parser: llm_parser
  - data_ingestion: data_ingestion

dataset_path: data
vectorstore_path: vectorstore
docstore_path: docstore.pkl
collection_name: rag_fusion_collection
embedding_model: sentence-transformers/all-MiniLM-L6-v2 # Use BAAI/bge-large-en-v1.5 for higher accuracy
device: cuda # or cpu, depending on your hardware
rag_fusion:
  enabled: true # Set to false if you want to disable RAG Fusion
  fusion_strategy: weighted_average # or max, depending on your preference
  fusion_threshold: 0.5 # Threshold for fusion, adjust based on your data quality
  generated_query_count: 5 # Number of queries to generate for each input
